# Generated by Django 3.2.5 on 2021-07-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_requests', '0002_auto_20210703_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordrequestfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
