# Generated by Django 3.2.5 on 2021-07-21 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_requests", "0006_alter_recordrequestfile_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Correspondence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from", models.CharField(max_length=256)),
                ("to", models.CharField(max_length=256)),
                ("subject", models.CharField(max_length=256)),
                ("body", models.TextField()),
                ("date", models.DateTimeField()),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record_requests.recordrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="recordrequestfile",
            name="correspondence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="record_requests.correspondence",
            ),
        ),
    ]
