version: '3'

volumes:
  local_postgres_data:
  minio:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pra_request_tracker_local_django
    container_name: django
    depends_on:
      - postgres
      - minio
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:13
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - .env

  minio:
    image: minio/minio
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
    env_file:
       - .env
    environment:
      MINIO_ROOT_USER: minio
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbucket:
    image: minio/mc
    env_file:
       - .env
    depends_on:
      - minio
    # Add the desired bucket, and set its policy to public
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${AWS_STORAGE_BUCKET_NAME};
      /usr/bin/mc policy set public myminio/${AWS_STORAGE_BUCKET_NAME};
      exit 0;
      "
