version: '3'

volumes:
  postgres_data:
  static:


services:
  redis:
    image: redis
    expose:
      - 6379

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: pra_request_tracker_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: /start
    networks:
      - default
    ports:
      - "6667:5000"
    volumes:
      - static:/app/staticfiles
