version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  static_files:
    name: pra-request-tracker-static


services:
  redis:
    image: redis
    expose:
      - 6379

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: pra_request_tracker_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - .env

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: pra_request_tracker_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: /start
    networks:
      - protonmail
      - default
    ports:
      - "6667:5000"
    volumes:
      - static_files:/usr/src/app/pra_request_tracker/static

networks:
  protonmail:
    external: True
