version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  redis:
    image: redis
    expose:
      - 6379

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: pra_request_tracker_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - .env

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: pra_request_tracker_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: /start
    networks:
      - protonmail
      - default

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: pra_request_tracker_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "6667:80"

networks:
  protonmail:
    external: True
