# Generated by Django 3.1.7 on 2021-07-01 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "verbose_name_plural": "Agencies",
            },
        ),
        migrations.CreateModel(
            name="RecordRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Processing"),
                            ("ack", "Awaiting Acknowledgement"),
                            ("processed", "Awaiting Response"),
                            ("appealing", "Awaiting Apeal"),
                            ("fix", "Fix Required"),
                            ("payment", "Payment Required"),
                            ("lawsuit", "In Litigation"),
                            ("rejected", "Rejected"),
                            ("no_docs", "No Responsive Documents"),
                            ("done", "Completed"),
                            ("partial", "Partially Completed"),
                            ("abandoned", "Withdrawn"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record_requests.agency",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecordRequestFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="")),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(null=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record_requests.recordrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
