# Generated by Django 3.1.7 on 2021-06-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={"verbose_name_plural": "Agencies"},
        ),
        migrations.RemoveField(
            model_name="recordrequestfile",
            name="url",
        ),
        migrations.AddField(
            model_name="recordrequestfile",
            name="file",
            field=models.FileField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
