# Generated by Django 3.1.7 on 2021-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordrequest",
            name="estimated_response_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="recordrequest",
            name="filed_at",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="recordrequest",
            name="last_communication_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="recordrequest",
            name="tracking_number",
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="name",
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="recordrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Apeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                    ("review", "In Review"),
                    ("install", "Installments"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
