# Generated by Django 3.1.7 on 2021-06-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_requests", "0002_auto_20210630_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordrequest",
            name="title",
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recordrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Apeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
