# Generated by Django 3.1.7 on 2021-06-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_requests", "0004_auto_20210630_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordrequestfile",
            name="title",
            field=models.CharField(default="Gib kitten", max_length=256),
            preserve_default=False,
        ),
    ]
