name: Lint and Test

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: DOCKER_COMPOSE=docker-compose make install
      - name: Run pre-commit checks
        run: DOCKER_COMPOSE=docker-compose make lint

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Run mypy
        run: DOCKER_COMPOSE=docker-compose make types

  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Run pytest
        run: DOCKER_COMPOSE=docker-compose make test
