name: Lint and Test

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: extractions/setup-just@v1
      - name: Install Dependencies
        run: just install
      - name: Run pre-commit checks
        run: just lint

  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      -
        name: Run pytest
        run: just test
