name: Lint and Test

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: make install
      - name: Run pre-commit checks
        run: make lint

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Run mypy
        run: make types

  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Run pytest
        run: make test
